version: '3.8'

services:
  wazuh.manager:
    image: wazuh/wazuh:4.7.5
    container_name: wazuh-manager
    hostname: wazuh-manager
    ports:
      - "1514:1514/udp"   # syslog/agent
      - "1515:1515"       # agent enrollment
      - "55000:55000"     # Wazuh API
    volumes:
      - wazuh_data:/var/ossec/data

  wazuh.dashboard:
    image: wazuh/dashboard:4.7.5
    container_name: wazuh-dashboard
    environment:
      - WAZUH_API_URL=https://wazuh.manager:55000
      - WAZUH_API_USER=admin
      - WAZUH_API_PASSWORD=SecretPassword
      - DASHBOARDS_PASSWORD=SecretPassword
      - WAZUH_SSL_VERIFY=false
    ports:
      - "5602:5601"  # Wazuh dashboard (Kibana-based)
    depends_on:
      - wazuh.manager

volumes:
  wazuh_data:
    driver: local


