input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # pass-through; add tags/index override if needed
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cv_project-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}


